# Generated by Django 5.0.1 on 2024-01-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='Media/img'),
        ),
    ]
