# Generated by Django 5.0.1 on 2024-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_requirements_whatyoulearn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='points',
            field=models.CharField(max_length=800),
        ),
    ]
