# Generated by Django 5.0.1 on 2024-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='certificate',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
