# Generated by Django 5.0.1 on 2024-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_video_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='certificate',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
