# Generated by Django 5.0.1 on 2024-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_video_certificate_course_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
