# Generated by Django 5.0.1 on 2024-01-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_author_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=100)),
                ('qemail', models.CharField(max_length=100)),
                ('qquestion', models.TextField()),
            ],
        ),
    ]
