# Generated by Django 5.0.1 on 2024-05-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=4, null=True),
        ),
    ]
